### ISSUE TITLE
Microsoft.Azure.CosmosDB.BulkExecutor package depends on wrong version of Microsoft.Azure.DocumentDB 

### ISSUE THREAD

**Issue by AArnott** [Azure/azure-cosmosdb-dotnet#577]
Your [`Microsoft.Azure.CosmosDB.BulkExecutor` package](https://www.nuget.org/packages/Microsoft.Azure.CosmosDB.BulkExecutor/1.0.2) claims to depend on [Microsoft.Azure.DocumentDB, v1.21.1](https://www.nuget.org/packages/Microsoft.Azure.DocumentDB/1.21.1) but in fact it fails at compile time if you call particular methods because in fact (and your own samples [corroborate this](https://github.com/Azure-Samples/azure-cosmosdb-graph-bulkexecutor-dotnet-getting-started/blob/bd1e7eae99767fa65224d55fe43ac2d51ee80d29/GraphBulkExecutorSample/GraphBulkExecutorSample/packages.config#L4)) it depends on v2.0.0-preview of the Microsoft.Azure.DocumentDB package.

Can you push a new `Microsoft.Azure.CosmosDB.BulkExecutor` package that fixes the dependency information so it isn't broken by default?

**Comment by jackbond** [comment]
I thought maybe it was just the project file that was referencing the higher version, so I went ahead and converted the project to use packagereferences instead. Sure enough, despite the nuget dependencies showing that the library only requires Microsoft.Azure.DocumentDB (>= 1.21.1), it failed to compile.

It's truly sad that once again this team...

1) Completely ignores the community (no response to this question in six days)
2) Seems unfamiliar with the latest Microsoft technologies (netstandard, packagereferences)
3) Publishes a 100% garbage Nuget

Where's the testing? I've said it before, and I'll say it again, if I had a team that displayed this level of workmanship, someone would have been fired ages ago.

**Comment by rnagpal** [comment]
@AArnott : Thanks for reporting this. We will fix this soon and will release an updated BulkExecutor package by this week. Meanwhile, please upgrade the DocumentDB SDK version to **2.0.0-preview** in your application to workaround this issue.

**Comment by rnagpal** [comment]
@AArnott : We have released a new version(1.1.0) of BulkExecutor that fixes this issue. It now depends on 2.0.0 version of .NET SDK. The sample also has been updated. We will be updating the Release Notes shortly to mention What's new in this version.

**Comment by AArnott** [comment]
Using the latest version of your package, I can now compile without other package refs, but at runtime it still fails:

```cs
var graphBulkImporter = new GraphBulkExecutor(this.docClient, this.graph);
await graphBulkImporter.InitializeAsync(); // exception thrown here:
```

> System.MissingMethodException: 'Method not found: 'System.Threading.Tasks.Task`1<Microsoft.Azure.Documents.Routing.CollectionRoutingMap> Microsoft.Azure.Documents.Routing.PartitionKeyRangeCache.TryLookupAsync(System.String, Microsoft.Azure.Documents.Routing.CollectionRoutingMap, System.Threading.CancellationToken)'.'

What's going on here? Are you still compiling against a different version than you have a package reference to?

**Comment by lucacestola** [comment]
I get the same error running the sample at [https://github.com/Azure/azure-cosmosdb-bulkexecutor-dotnet-getting-started](https://github.com/Azure/azure-cosmosdb-bulkexecutor-dotnet-getting-started).

I've updated the packages version as follow, but still facing the exception during InitializeAsync.

```xml
<packages>
  <package id="Microsoft.Azure.CosmosDB.BulkExecutor" version="1.1.0" targetFramework="net452" />
  <package id="Microsoft.Azure.DocumentDB" version="2.0.0" targetFramework="net452" />
</packages>
```

Any suggestion?
